'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Electronics.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Device,VZ Min,VZ @ IZ,VZ Max,IZ,ZZ @ IZ, ZZ @ IZK,IZK,IZM,PD
        '''1N4728A,3.135,3.3,3.465,0.076,10,400,0.001,1.38,1
        '''1N4729A,3.42,3.6,3.78,0.069,10,400,0.001,1260,1
        '''1N4730A,3.705,3.9,4.095,0.064,9,400,0.001,1190,1
        '''1N4731A,4.085,4.3,4.515,0.058,9,400,0.001,1070,1
        '''1N4732A,4.465,4.7,4.935,0.053,8,500,0.001,970,1
        '''1N4733A,4.845,5.1,5.355,0.049,7,550,0.001,890,1
        '''1N4734A,5.32,5.6,5.88,0.045,5,600,0.001,810,1
        '''1N4735A,5.89,6.2,6.51,0.041,2,700,0.001,730,1
        '''1N4736A,6.46,6.8,7.14,0.037,3.5,700,0.001,660,1
        '''1N4737A,7 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Zener() As String
            Get
                Return ResourceManager.GetString("Zener", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
